version: '3'
services:
  web:
    env_file: ./.env
    networks: 
      - app_net 
    build: 
      context: ./configuration/nginx
      dockerfile: Dockerfile
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    environment: 
      HOST_USER_UID: ${HOST_USER_UID}
      HOST_USER_GID: ${HOST_USER_GID}
    ports:
      - "${NGINX_PORT}:80"
    restart: ${RESTART}
    volumes:
      - './code:/code:cached'
      - "${NGINX_VHOST_DIR}:/etc/nginx/conf.d/"
      - './configuration/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './logs/nginx:/var/log/nginx'

  mysql:
    env_file: ./.env
    networks:
      - app_net
    build: 
      dockerfile: Dockerfile
      context: ./configuration/mysql
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
    volumes:
      - './data/mysql:/var/lib/mysql'
      - './shared:/shared'
    restart: ${RESTART}
    environment: 
      MYSQL_VERSION: ${MYSQL_VERSION}
      HOST_USER_UID: ${HOST_USER_UID}
      HOST_USER_GID: ${HOST_USER_GID}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
  php72:
    env_file: ./.env
    networks:
      - app_net
    build: 
      context: ./configuration/php/php72
      dockerfile: Dockerfile
      args: 
        PHP7_VERSION: 7.2
    environment:
      HOST_USER_UID: ${HOST_USER_UID}
      HOST_USER_GID: ${HOST_USER_GID}
    expose:
      - '9003'
    restart: ${RESTART}
    volumes:
      - './code:/code:cached'
      - './configuration/php/www.conf:/usr/local/etc/php-fpm.d/zz-docker.conf'
      - './configuration/php/php72/fpm.conf:/usr/local/etc/php-fpm.conf'
      - './configuration/php/php72/ext:/usr/local/etc/php/conf.d'
      - './configuration/php/php72/php.ini:/usr/local/etc/php/php.ini'
    working_dir: /code

networks:
  app_net:
    ipam:
      config:
        - subnet: 10.0.0.0/24
          #gateway: 10.0.0.1
