GET http://cym.loc/users
X-Debug-Token: PHPSTORM
X-Debug-Token-Link: http://cym.loc/_profiler/PHPSTORM
X-Previous-Debug-Token: PHPSTORM
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiYXNkZiIsInVzZXJfaWQiOiIxIiwiZXhwIjoxNTM3NTMzMTMyfQ.qyt47etPnCe6RqUJL1g8gBo4-Z5ZXrH55WgHlc-zJGU


###
